### ISSUE TITLE
Include schedule sms

### ISSUE THREAD

**Issue by varunotelli** [varunotelli/Py2SMS#2]

**Comment by SathieshMahadevu** [comment]
Collecting py2sms
  Using cached https://files.pythonhosted.org/packages/db/61/8e9786b58111c0aec33f6bf108280c503b0a469c3a4cf698cd88642e136a/py2sms-1.1.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\gcelab\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GCELAB\\AppData\\Local\\Temp\\pip-install-yg1ffkaw\\py2sms\\setup.py'"'"'; __file__='"'"'C:\\Users\\GCELAB\\AppData\\Local\\Temp\\pip-install-yg1ffkaw\\py2sms\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\GCELAB\AppData\Local\Temp\pip-install-yg1ffkaw\py2sms\pip-egg-info'
         cwd: C:\Users\GCELAB\AppData\Local\Temp\pip-install-yg1ffkaw\py2sms\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\GCELAB\AppData\Local\Temp\pip-install-yg1ffkaw\py2sms\setup.py", line 11, in <module>
        long_description=open('README.MD').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.MD'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
