### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fatalcoder524** [varunotelli/Py2SMS#4]
pip install py2sms
Collecting py2sms
  Using cached https://files.pythonhosted.org/packages/db/61/8e9786b58111c0aec33f6bf108280c503b0a469c3a4cf698cd88642e136a/py
2sms-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\fatalcoder524\AppData\Local\Temp\pip-install-lkfm5e2d\py2sms\setup.py", line 11, in <module>
        long_description=open('README.MD').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.MD'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\fatalcoder524\AppData\Local\Temp\pip-install-lkfm5e2
d\py2sms\

**Comment by tinshade** [comment]
Same error

**Comment by rohan-arora-99** [comment]
same error

**Comment by Suryanandsingh** [comment]
Same error

**Comment by SathieshMahadevu** [comment]
same errror

**Comment by ABHIJITBURMAN** [comment]
Same error. need solution.

**Comment by fatalcoder524** [comment]
I doubt this project is still working. You can try by downloading this project as zip and importing the __init__.py . You can direct download from GitHub or using wget in Linux.
